### ISSUE TITLE
Problème sur clavier AZERTY / QWERTY

### ISSUE THREAD

**Issue by micbuffa** [gamesonweb/be-green-charlie-project#2]
Hello, comme je vous l'ai dit le jeu n'est pas top en clavier AZERTY. Vous devriez rapidement ajouter une option pour choisir son clavier. Une vidéo de gameplay pour le jury serait un gros plus :-)

**Comment by Riochine** [comment]
Le qwerty et azerty est dorénavant possible ! Une video de gameplay est aussi disponible.
